version: '3.8'

services:
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - MONGO_URL=mongodb://mongo:27017/chatbot
      - JWT_SECRET=supersecret
    depends_on:
      - mongo
    volumes:
      - .:/app
      - /app/node_modules
    command: npm run start:dev # Para desenvolvimento com hot reload

  mongo:
    image: mongo:6
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data:
